application: hitchlessinvoicing
version: 1
runtime: python
api_version: 1

handlers:
- url: /assets/css
  static_dir: views/assets/css

- url: /assets/js
  static_dir: views/assets/js

- url: /assets/img
  static_dir: views/assets/img
  
- url: .*
  script: main.py
  secure: always

builtins:
- datastore_admin: on
